import os
import time
cmdclear = ("clear")
rescl = os.system(cmdclear)
cmd0 = ("figlet = welcome beautiful! = | lolcat")
res0 = os.system(cmd0)
welcome=input("enter command(h for help or x to exit)=>")
while welcome == "":
    cmd098777 = ("cowsay enter command or type x to exit | lolcat")
    res000000 = os.system (cmd098777)
    time.sleep(1)
    welcome=input("enter command(h for help or x to exit=>)")
if welcome == "enable zsh":
    cmdzsh = ("zsh")
    zshres = os.system (cmdzsh)
if welcome == "vivaldi":  
    cmdviv = ("figlet ++VIVALDI++ | lolcat")
    vivres =   os.system(cmdviv)
    time.sleep(2)
    cowviv = ("cowsay starting vivaldi... | lolcat")
    cowres = os.system(cowviv)
    time.sleep(3)
    vivaldi = ("vivaldi")
    vivstart = os.system (vivaldi)
if welcome == "discord":
    cmddiscord = ("figlet ++DISCORD++ | lolcat")
    discordres = os.system(cmddiscord)
    time.sleep(2)
    cowdis = ("cowsay starting discord.. | lolcat")
    cowres = os.system(cowdis)
    time.sleep(3)
    discord = ("discord")
    disstart = os.system (discord)
if welcome == "find file":
    fzf = ("cowsay OK LETS FIND | lolcat")
    fzfres = os.system(fzf)
    time.sleep(1)
    fzfban = ("figlet finder | lolcat")
    fzfbanres = os.system(fzfban)
    time.sleep(2)
    fzffinder = ("fzf")
    finderres = os.system(fzffinder)
if welcome == "check updates":
    cmdupdate = ("cowsay lets check! | lolcat")
    updateres = os.system(cmdupdate)
    time.sleep(1)
    updatebanner = ("figlet update checker | lolcat")
    resup = os.system (updatebanner)
    time.sleep(2)
    update = ("pacman -Syyu")
    updateres = os.system(update)
if welcome == "show system storages":
    cmdst = ("cowsay OK please wait.... | lolcat")
    resst = os.system (cmdst)
    time.sleep(2)
    dufban = ("figlet storages | lolcat")
    dufbares = os.system (dufban)
    time.sleep(1)
    duf = ("duf")
    dufres = os.system (duf)
if welcome == "show system information":
    cowsay = ("cowsay take time to me to show... | lolcat")
    resinfo = os.system(cowsay)
    time.sleep(2)
    banner = ("figlet system info | lolcat")
    resbanner = os.system(banner)
    neofetch = ("neofetch")
    resneo = os.system(neofetch)
if welcome == "check internet":
    cmd666 = ("cowsay starting internet checker... | lolcat")
    ress = os.system(cmd666)
    time.sleep(2)
    cmdcheck = ("figlet internet checker | lolcat ")
    ressss = os.system(cmdcheck)
    time.sleep(2)
    cmdping = ("ping 8.8.8.8")
    ress2 = os.system(cmdping)
if welcome == "create txt file":
    cmd2 = ("touch file.txt")
    cmd00000 = ("cowsay DONE! | lolcat")
    res = os.system(cmd2)
    resdone = os.system(cmd00000)
if welcome == "create python file":
    cmd2 = ("touch file.py")
    cmd999 = ("cowsay DONE! | lolcat")
    resdone = os.system(cmd999)
    res = os.system(cmd2)
if welcome == "tmux":
    cmd9 = ("tmux")
    res44= os.system(cmd9)
if welcome == "play music":
    cmd021 = ("cowsay please wait.... | lolcat")
    res321 = os.system(cmd021)
    time.sleep(2)
    cmd3 = ("kew")
    res = os.system(cmd3)
if welcome == "browser":
    print("wait....")
    time.sleep(2)
    cmd4 = ("links www.duckduckgo.com")
    res = os.system(cmd4)
if welcome == "system control":
    print("loading...")
    time.sleep(2)
    cmd5 = ("btop")
    res = os.system(cmd5)
if welcome == "file manager":
    print("ranger is loading your files....")
    time.sleep(2)
    cmd6 = ("ranger")
    res = os.system(cmd6)
if welcome == "text editor":
    print("please wait...")
    time.sleep(1)
    cmd6 = ("micro")
    res = os.system(cmd6)
if welcome == "calculator":
    cmd9091 = ("cowsay loading.... | lolcat")
    res4444 = os.system(cmd9091)
    time.sleep(2)
    cmd7 = ("bc |lolcat")
    cmd9090 = ("cowsay DONE! NOW YOU CAN USE THIS CALCULATOR | lolcat")
    RES4444 = os.system(cmd9090)
    res77777 = os.system(cmd7)
if welcome == "check battry":
    cmd98765 = ("cowsay === loading info  === | lolcat")
    res5647 = os.system(cmd98765)
    time.sleep(2)
    cmd70 = ("acpi | lolcat")
    res = os.system(cmd70)
if welcome == "h":
    cmd000=("cowsay loading help menu.... | lolcat")
    res650=os.system(cmd000)
    time.sleep(2)
    cmdfinish = ("clear")
    res6666 = os.system(cmdfinish)
    cmd999=("figlet = HELP MENU =  | lolcat")
    res655=os.system(cmd999)
    cmd8 = print('//WELCOME TO MY COMMANDS SCRIPT// COOMANDS==>//create files(py and txt)=> create txt file(for .txt)and create python file(for .py)/play music => launch kew music player/ browser => launch links web browser/ system control => launch btop system monitor/ file manager => launch ranger file manager/ text editor => launch micro text editor/ calculator => basic calculator(bc)/ tmux => launch tmux for have better performance with terminal// check internet => check the connection with ping // show system information => neofetch command// check updates => check for any updates with pacman -Syyu command// find file => find any files you want with fzf command// show system storages => show all system storages with duf command// enable zsh => start ohmyzsh shell ')
    cmd9876 = ("cowsay thank you for using my script! | lolcat")
    res09876 = os.system(cmd9876)
if welcome ==  "show version" :
    cmd90 = ("cowsay === 1.0 === | lolcat")
    res90 = os.system(cmd90)
if welcome == "x":
    cmdcl=("clear")
    resex=os.system(cmdcl)
    exit()
